del /s/q .\MDK\*.dep
del /s/q .\MDK\*.bak
del /s/q .\MDK\*.o
del /s/q .\MDK\*.d
del /s/q .\MDK\*.i
del /s/q .\MDK\*.__i
del /s/q .\MDK\*.administrator
del /s/q .\MDK\*.htm
del /s/q .\MDK\*.tra
del /s/q .\MDK\*.lnp
del /s/q .\MDK\*.plg
del /s/q .\MDK\*.lst
del /s/q .\MDK\*.uvgui.*
del /s/q .\MDK\*.tmp
del /s/q .\MDK\*.crf
del /s/q .\MDK\*.map
del /s/q .\MDK\*.cout
del /s/q .\MDK\*.pbi
del /s/q .\MDK\*.pbd
del /s/q .\MDK\*.cfg
del /s/q .\MDK\*.fop
del /s/q .\MDK\*.axf
del /s/q .\MDK\*.iex
del /s/q .\MDK\*.pbd.*
del /s/q .\MDK\JLinkLog.txt